version: '4'
services:
  dns:
    build:
      context: .
      dockerfile: DNSDockerfile
    container_name: dns-server
    networks:
      vdnsnet:
        ipv4_address: 192.168.0.10

  client:
    build:
      context: .
      dockerfile: ClientDockerfile
    container_name: dns-client
    networks:
      vdnsnet:
        ipv4_address: 192.168.0.20
    depends_on:
      - dns

  email:
    image: namshi/smtp
    container_name: email-server
    environment:
      - MAILNAME=mail.mis.lan
      - SMARTHOST_ADDRESS=smtp.example.com
      - SMARTHOST_PORT=587
      - SMARTHOST_USER=user@example.com
      - SMARTHOST_PASSWORD=password
    networks:
      vdnsnet:
        ipv4_address: 192.168.0.25

networks:
  vdnsnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24
