version: '3.8'

services:
  dns-server:
    image: bind9-official-image:latest  # Ersetze bind9-official-image mit dem korrekten Image-Namen
    container_name: bind9
    volumes:
      - ./bind9_conf:/etc/bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - dnsnet

  mail-server:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    env_file:
      - mailserver.env
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    networks:
      - dnsnet
    depends_on:
      - dns-server

  dns-client:
    image: ubuntu:20.04
    container_name: dns-client
    command: tail -f /dev/null
    networks:
      - dnsnet
    depends_on:
      - dns-server

networks:
  dnsnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/24

volumes:
  maildata:
  mailstate:
  maillogs:
