version: '3.8'

services:
  dns:
    container_name: dns
    build:
      context: .
      dockerfile: DNSDockerfile
    ports:
      - "53:53/udp"  # Öffnet UDP für den DNS-Server auf dem Host
      - "53:53/tcp"  # Öffnet TCP für den DNS-Server auf dem Host
    volumes:
      - "./named.conf.default-zones:/etc/bind/named.conf.default-zones"
      - "./db.mis:/etc/bind/db.mis"
    networks:
      publicnet:
        ipv4_address: 192.168.50.10  # Öffentliche IP im gebridgeden Netzwerk
      privatenet:
        ipv4_address: 192.168.100.10  # Private IP im internen Netzwerk

  client1:
    container_name: client
    build:
      context: .
      dockerfile: ClientDockerfile
    dns:
      - 192.168.100.10  # Nutzt den DNS-Server über das interne Netzwerk
    networks:
      privatenet:  # Nur im internen Netzwerk, nicht gebridged
    stdin_open: true
    tty: true

networks:
  publicnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.50.0/24  # Subnetz für das öffentliche Netzwerk

  privatenet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24  # Subnetz für das private Netzwerk
